### ISSUE TITLE
Implement initial invokeai-container

### ISSUE THREAD

**Issue by entelecheia** [entelecheia/invokeai-container#1]
## Summary

Implement a Docker container to run InvokeAI with Stable Diffusion and GPT models.

## Tasks

- [ ] Create Dockerfile
  - Use Python base image
  - Install InvokeAI and dependencies 
- [ ] Copy InvokeAI source code
- [ ] Create entrypoint script
  - Start InvokeAI server on container startup
- [ ] Expose port 7500
  - For InvokeAI web UI
- [ ] Include base InvokeAI config
  - Stable Diffusion and GPT models
- [ ] Create config volume
  - For mounting custom config files  
- [ ] Write README
  - Usage
  - Models
  - Configs
  - Ports
  
## Requirements

- Dockerfile builds InvokeAI image
- Entrypoint launches InvokeAI server on start
- Port 7500 exposed for web UI
- Base InvokeAI config included
- Config volume for custom configs
- README explains usage and configuration

## Resources

- InvokeAI repo: https://github.com/invoke-ai/InvokeAI
